# WARNING: Insecure pod manifest for testing only
apiVersion: v1
kind: Pod
metadata:
  name: vulnerable-pod
spec:
  containers:
  - name: nginx
    image: nginx:1.14
    securityContext:
      privileged: true
    env:
    - name: SECRET_TOKEN
      value: "super-secret-token"
    ports:
    - containerPort: 80
    volumeMounts:
    - name: host-etc
      mountPath: /host-etc
  volumes:
  - name: host-etc
    hostPath:
      path: /etc
      type: Directory
